### ISSUE TITLE
Publish a package on pypi

### ISSUE THREAD

**Issue by Toniob** [Arvedui/radicale-dovecot-auth#4]
Hi,

It would be great to have the package published on pypi. It will give it visibility, possibly more contributions and it would be easier to install.

Thanks

**Comment by Arvedui** [comment]
I will put in on my todo, but it might take a few days.

**Comment by Arvedui** [comment]
Done :)

**Comment by LinLo** [comment]
Hello,
I'm trying to package this module for my gentoo.
Could you fix the name "docecot" to "dovecot" in pypi release ?
Thank you :)

**Comment by Arvedui** [comment]
Oh god, that's embarrassing. It's fixed, as in I created a new package with the correct name since renames are not possible, now.
Thanks for pointing this out!
