### ISSUE TITLE
Avoid import radicale-dovecot-auth from setup.py

### ISSUE THREAD

**Issue by slavkoja** [Arvedui/radicale-dovecot-auth#7]
Importing radicale-dovecot-auth module from setup.py breaks basic debian's packaging workflow, because it not possible to clean package's tree without full radicale-dovecot-auth's build dependencies installed.

These dependencies are of course needed to build package, but in my case i use separate chroot to build packages (pbuilder), but i cannot use eg. debclean tool, because it fails to run setup.py due missing dependencies. When i patched (v0.2.1) to remove mentioned import and add exact version number, all works as expected. But this is not a solution, while i will easily forget to correct version number in future versions...

Please, consider to move version info out of radicale-dovecot-auth module, as i can see, it is used only in setup.py.

**Comment by Arvedui** [comment]
The point of the version info being in the module itself is that the module knows it's own version. I consider that good practice.
And if I had it in more that one place I would be the one to forget to update it somewhere …

But I agree that the way I currently handle this is suboptimal, I will figure something else out.

**Comment by slavkoja** [comment]
I understand and hope, that you will find good solution...

**Comment by Arvedui** [comment]
Can you check if it works with current master?

**Comment by slavkoja** [comment]
I tried the debclean and it works as expected now. I tried to build the package too and it works. I didn't test in radicale yet, thanks. Can you do new version release, please?

I noticed, that you skip the Python 3.7 in setup.py, is it intended? The next debian release will have 3.7, i am testing it on 3.7 and it worked (before this version change) for me. Or i have to create separate issue for this?

**Comment by Arvedui** [comment]
Not intentional more like a typo …

Thank you, will release a new version soon.

**Comment by slavkoja** [comment]
If are you interested, [here](https://debs.slavino.sk/pool/main/r/radicale-dovecot-auth/) are debian (stable & testing) packages, i deployed the 0.3.0 version to my own radicale server and it seems to work as expected ;-)

**Comment by Arvedui** [comment]
I'm not using debian but I'm thinking about expanding the Installation section in the readme, may I mention you repository?

**Comment by slavkoja** [comment]
You can, of course, but i am in domain change process, then it will be valid only for same months, until domain expires. If you are really interested, i can ping back after i finish this.

**Comment by slavkoja** [comment]
OK, i finished the process with result: no domain change, then you can link packages, if you want ;-)

**Comment by Arvedui** [comment]
Thank you!
